### ISSUE TITLE
basic HTTP request interface for editing fields

### ISSUE THREAD

**Issue by vlee489** [inkfarer/ipl-overlay-controls#78] opened 2022-01-11 22:57 UTC
Add the ability to enable a basic HTTP interface to edit the details of replicants

example 
- POST to update team score
- GET to retrieve the team's colour
- POST that will update comms from Radia API
- POST to reveal comms box on the main scene
- POST to show/hide scorebox on the main scene

This API could be used to interface with physical control interfaces such as a Stream Deck or with [Bitfocus Companion ](https://bitfocus.io/companion/)

**Comment by inkfarer** [comment] 2022-01-31 00:39
This was resolved in a different way, by interfacing with the NodeCG websocket directly. 
Closing as the issue is no longer necessary.

**Closed as completed by inkfarer** 2022-01-31 00:39 UTC
Labels: feature
